### PR TITLE
Update licenses and include CC BY-NC-ND as license option

### PR DESCRIPTION
**Pull request by murpii**

### CODE REVIEW

**Comment by heinrich5991** [comment]
I'd prefer not allowing -ND / -NC.

**Comment by edg-l** [comment]
I prefer not allowing -ND, no opinion on NC

**Comment by heinrich5991** [comment]
-ND is really bad for DDNet as it doesn't allow us to change the file for a different skin format etc.

Both -ND and -NC are considered non-free licenses and it means we cannot ship them with the client if we want to be considered open-source.

**Comment by edg-l** [comment]
I ratify, im also against NC

**Pull request closed without merging**
